# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d16b995a26da7727930c876efc615ef37c108f54ce1df71a30566a86c43c49ee2a4c2369cc8ee9865e90dd6a4c5c77972f96cc28c2f7ba2c816d468a4d8cda0

test:
  secret_key_base: 89de21d99fe04167241b24c98164c0b1dc7862da5eb42cdfa221101b9ecf88a5ca9919db2307e79ca9eaf5f7be9ff49989f76ee062762905028da8ee446b09da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
